Changes to Commit 3
Adding description to the Table. Still has problem of rendering it into a pdf file. I received a error message shows: compilation failed- error
LaTeX Error: Too deeply nested.